version: '3.5'
services:

#mysql service
  db: 
    container_name: mysql_db
    restart: always
    image: mysql:latest
    ports:
      - "3360:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - "./my-cnf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"
    networks:
      static_ip:
        ipv4_address: 172.18.1.1


#users service
  users:
    container_name: users
    build: ./server/users
    ports: 
      - 8080:8080 
    restart: always
    depends_on:
      - db
    networks:
      static_ip:
        ipv4_address: 172.18.1.2

#books service
  books:
    container_name: books
    build: ./server/books
    ports: 
      - 8081:8081 
    restart: always
    depends_on:
      - db
    networks:
      static_ip:
        ipv4_address: 172.18.1.3        
  
  #frontend service
  frontend:
    container_name: frontend
    build: ./client/
    ports: 
      - 3000:3000 
    restart: always
    networks:
      static_ip:
        ipv4_address: 172.18.1.4

# #nginx reverse proxy microservice
#   proxy:
#     build: ./proxy
#     container_name: nginx-proxy
#     ports:
#       - "80:80"
#       - "443:443"
#     networks:
#       static_ip:
#         ipv4_address: 172.18.1.4



networks:
  static_ip:
    name: booksshelf-network
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/20
